title: Sanne Smith
email: sannesmith@stanford.edu
description: Personal website of Sanne Smith, lecturer and Education Data Science MS Program Director at the Stanford Graduate School of Education
#baseurl: /
url: "" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: mmistakes/minimal-mistakes
#https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin
#minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "default"
search: true
search_full_content: true
lunr:
  search_within_pages: true
include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

author:
  avatar : "/assets/images/Sanne Smith.jpg"
  bio    : ""
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sanne_m_smith"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sannemsmith"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sannesmith/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sanne_m_smith"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sannemsmith"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sannesmith/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
